name: Sonar Check
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: maltush_python-project-50
          SONAR_ORGANIZATION: maltush
        with:
          args: >
            -Dsonar.coverage.exclusions=tests/**
            -Dsonar.exclusions=tests/**
      - name: Run linter and pytest
        run: |
          make lint
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true